# See https://pre-commit.com for more information
# See https://pre-commit.com/#installation for installation instructions
# See https://pre-commit.com/hooks.html for more hooks
#
# use `git commit --no-verify` to disable git hooks for this commit

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: check-yaml
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "1.5.2"
  hooks:
    - id: pyproject-fmt
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.6
  hooks:
  - id: ruff-format
  - id: ruff
    args: [ "--fix", "--unsafe-fixes", "--exit-non-zero-on-fix"]
# mypy args:
#   must include --ignore-missing-imports for mypy.  It is included by default
#     if no arguments are supplied, but we must supply it ourselves since we
#     specify args
#   cannot use --warn-unused-ignores because it conflicts with
#     --ignore-missing-imports
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy
    args: ['--warn-unused-ignores', '--strict-equality','--no-implicit-optional', '--check-untyped-defs']
    exclude: 'testdata/test_package_specifier/local_extras/setup.py'
