language: python
os: linux
cache:
  pip: true
matrix:
  include:
    - python: "3.6"
      env: NOXSESSION="tests-3.6"
    - python: "3.7"
      env: NOXSESSION="tests-3.7"
      dist: xenial
    - python: "3.7"
      env: NOXSESSION="lint"
      dist: xenial
    - python: "3.7"
      env: NOXSESSION="docs"
      dist: xenial
    - os: windows
      language: bash
      env: NOXSESSION="tests-3.7"
      before_install:
        - export TRAVIS_PYTHON_VERSION=3.7
        - choco install python --version $TRAVIS_PYTHON_VERSION
        - export PATH="/C/Python37:/C/Python37/Scripts:$PATH"
install:
  - pip install git+https://github.com/cs01/nox.git@5ea70723e9e6#egg=nox

script:
  - nox --non-interactive --session "$NOXSESSION"
