site_name: pipx
site_description: execute binaries from Python packages in isolated environments

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: pypa/pipx
repo_url: https://github.com/pypa/pipx
edit_uri: edit/main/docs/
extra:
  analytics:
    provider: 'google'
    property: 'UA-90243909-2'


nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Getting Started: "getting-started.md"
  - Docs: "docs.md"
  - Troubleshooting: "troubleshooting.md"
  - Examples: "examples.md"
  - Comparison to Other Tools: "comparisons.md"
  - How pipx works: "how-pipx-works.md"
  - Programs to Try: "programs-to-try.md"
  - Contributing: "contributing.md"
  - Changelog: "changelog.md"

markdown_extensions:
  - admonition  #  note blocks, warning blocks -- https://github.com/mkdocs/mkdocs/issues/1659

plugins:
  - search:
      lang: en
      enabled: true
  - gen-files:
      scripts:
        - scripts/gen_doc_pages.py
