[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
known_first_party = ["helpers", "package_info"]

[tool.pytest.ini_options]
markers = [
    "all_packages: test install with maximum number of packages",
]
