name: Create tests package lists for offline tests
on:
  workflow_dispatch:

jobs:
  create_package_lists:
    name: Create package lists
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip, Install nox
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Create lists
      run: |
        nox --non-interactive --session create_test_package_list-${{ matrix.python-version }}
    - name: Store reports as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lists
        path: testdata/tests_packages
